global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gatewayserver'
    # ⚠️ in prod — https
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8071' ]
    # ⚠️ Don't use in prod — for local self-signed certs only
    tls_config:
      insecure_skip_verify: true
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'assessments'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'assessments:8080' ]
  - job_name: 'notes'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notes:8090' ]
  - job_name: 'patients'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'patients:8100' ]
  - job_name: 'notifications'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notifications:8110' ]
