server:
  port: 8070

spring:
  application:
    name: eurekaserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  # Used to identify which metrics belong to which microservice
  metrics:
    tags:
        application: ${spring.application.name}
    # Enable histogram buckets for http.server.requests (required for histogram_quantile in Prometheus/Grafana)
    distribution:
      percentiles-histogram:
        http.server.requests: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
