server:
  port: 8090

spring:
  application:
    name: notes
  data:
    mongodb:
      uri: ${MONGODB_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  # Used to identify which metrics belong to which microservices
  metrics:
    tags:
      application: ${spring.application.name}
    # Enable histogram buckets for http.server.requests (required for histogram_quantile in Prometheus/Grafana)
    distribution:
      percentiles-histogram:
        http.server.requests: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

info:
  app:
    name: notes

logging:
  level:
    com:
      MedilaboSolutions:
        note: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"