services:
  k6:
    image: grafana/k6
    volumes:
      # Mounts the local 'perf-tests' folder into the container at '/scripts'
      - ../_perf-tests:/scripts
    entrypoint: ["k6", "run", "--insecure-skip-tls-verify", "/scripts/load/scenarios/loginPage.js"]
    networks:
      - medilabosolutions-net

networks:
  medilabosolutions-net:
    external: true