# FOR NOW, ALL THE CONTAINERS ARE IN THE SAME NETWORK

services:
  k6:
    image: grafana/k6
    volumes:
      - ../_tests-perf:/scripts
    entrypoint: ["k6", "run", "--insecure-skip-tls-verify", "/scripts/tests/realistic-traffic.js"]
    environment:
      USERNAME: ${USERNAME_K6}
      PASSWORD: ${PASSWORD_K6}
      FRONT_URL: ${FRONT_URL}
      BACK_URL: ${BACK_URL}
    networks:
      - docker-compose_medilabosolutions-net
    depends_on:
      front-vue:
        condition: service_healthy
    mem_limit: 1g
    mem_reservation: 512m

  front-vue:
    build:
      context: ../front-vue
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -an | grep :5173 | grep LISTEN"]
      interval: 5s
      retries: 5
    networks:
      - docker-compose_medilabosolutions-net
    mem_limit: 512m
    mem_reservation: 256m

networks:
  docker-compose_medilabosolutions-net:
    external: true
