server:
  port: 8110

spring:
  application:
    name: notifications
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  # Used to identify which metrics belong to which microservices
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

info:
  app:
    name: notifications

logging:
  level:
    com:
      MedilaboSolutions:
        assessment: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

mailtrap:
  token: ${MAILTRAP_API_TOKEN}
  inbox-id: ${MAILTRAP_SANDBOX_ID}

email:
  sender: ${EMAIL_SENDER}
  recipient: ${EMAIL_RECIPIENT}